baseURL = "www.goacademy.ee"
languageCode = "en-us"
title = "Go Academy Free Online Course"
#themesDir = "../.."
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Materials"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Check out the materials'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Go Academy Free Online Courses for Entrepreneurs."
    meta_og_title = "GoAcademy"
    meta_og_type = "website"
    meta_og_url = "https://www.goacademy.ee"
    meta_og_image = "/images/gologo.svg"
    meta_og_description = "Go Academy Free Online Courses"
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

  [params.logo]
      mobile = "/images/gologo.svg"
      standard  = "/images/gologo.svg"
